import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/Footer";
import { BaseUrlProvider } from "@/context/BaseUrlContext";
import { headers } from "next/headers";
import NavBarClient from "@/components/NavBarClient";
import { Separator } from "@/components/ui/separator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hds = await headers();
  const host = hds.get("x-forwarded-host") ?? hds.get("host");
  const proto = hds.get("x-forwarded-proto") ?? "https";
  const baseUrl = `${proto}://${host}`;

  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased   `}
        >
          <BaseUrlProvider value={baseUrl}>
            <NavBarClient />
           
            <main className="min-h-[75vh] bg-black">
              <div className="mt-[-30px] select-none bg-transparent shadow-lg shadow-amber-400">.</div>
              {children}
            </main>
            <div className="bg-transparent shadow-lg shadow-amber-400"><Separator/></div>
          </BaseUrlProvider>
          <Toaster />
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
